name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push backend image
      env:
        ECR_REGISTRY: "211125660832.dkr.ecr.us-west-2.amazonaws.com/backend"
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker buildx build --platform linux/amd64 -t $ECR_REGISTRY:latest -t $ECR_REGISTRY:$IMAGE_TAG ./backend --push

    - name: Build and push frontend image
      env:
        ECR_REGISTRY: "211125660832.dkr.ecr.us-west-2.amazonaws.com/frontend"
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker buildx build --platform linux/amd64 -t $ECR_REGISTRY:latest -t $ECR_REGISTRY:$IMAGE_TAG ./frontend --push

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.18.0'

    - name: Update kubeconfig
      env:
        AWS_REGION: "us-west-2"
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws eks --region $AWS_REGION update-kubeconfig --name pagos-test

    - name: Create db-secret.yaml
      env:
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: |
        echo "apiVersion: v1" > k8s/db-secret.yaml
        echo "kind: Secret" >> k8s/db-secret.yaml
        echo "metadata:" >> k8s/db-secret.yaml
        echo "  name: db-secret" >> k8s/db-secret.yaml
        echo "type: Opaque" >> k8s/db-secret.yaml
        echo "data:" >> k8s/db-secret.yaml
        echo "  DB_USERNAME: $(echo -n $DB_USERNAME | base64)" >> k8s/db-secret.yaml
        echo "  DB_PASSWORD: $(echo -n $DB_PASSWORD | base64)" >> k8s/db-secret.yaml

    - name: Deploy to EKS
      env:
        AWS_REGION: "us-west-2"
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        BACKEND_IMAGE: "211125660832.dkr.ecr.us-west-2.amazonaws.com/backend:${{ github.sha }}"
        FRONTEND_IMAGE: "211125660832.dkr.ecr.us-west-2.amazonaws.com/frontend:${{ github.sha }}"
      run: |
        kubectl apply -f k8s/db-secret.yaml
        kubectl apply -f k8s/backend-deployment.yaml
        kubectl apply -f k8s/backend-service.yaml
        kubectl apply -f k8s/frontend-deployment.yaml
        kubectl apply -f k8s/frontend-service.yaml
